# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\mantid\windows\Code\Mantid\scripts\Interface\ui\reflectometer/refl_save_window.ui'
#
# Created: Tue Apr 15 14:09:46 2014
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_SaveDialog(object):
    def setupUi(self, SaveDialog):
        SaveDialog.setObjectName(_fromUtf8("SaveDialog"))
        SaveDialog.resize(647, 418)
        SaveDialog.setSizeGripEnabled(True)
        self.layoutMain = QtGui.QGridLayout(SaveDialog)
        self.layoutMain.setObjectName(_fromUtf8("layoutMain"))
        self.buttonTransfer = QtGui.QPushButton(SaveDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonTransfer.sizePolicy().hasHeightForWidth())
        self.buttonTransfer.setSizePolicy(sizePolicy)
        self.buttonTransfer.setMinimumSize(QtCore.QSize(0, 0))
        self.buttonTransfer.setMaximumSize(QtCore.QSize(25, 16777215))
        self.buttonTransfer.setObjectName(_fromUtf8("buttonTransfer"))
        self.layoutMain.addWidget(self.buttonTransfer, 2, 1, 1, 1)
        self.layoutPrefix = QtGui.QHBoxLayout()
        self.layoutPrefix.setObjectName(_fromUtf8("layoutPrefix"))
        self.labelPrefix = QtGui.QLabel(SaveDialog)
        self.labelPrefix.setObjectName(_fromUtf8("labelPrefix"))
        self.layoutPrefix.addWidget(self.labelPrefix)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layoutPrefix.addItem(spacerItem)
        self.textPrefix = QtGui.QLineEdit(SaveDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textPrefix.sizePolicy().hasHeightForWidth())
        self.textPrefix.setSizePolicy(sizePolicy)
        self.textPrefix.setObjectName(_fromUtf8("textPrefix"))
        self.layoutPrefix.addWidget(self.textPrefix)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layoutPrefix.addItem(spacerItem1)
        self.layoutMain.addLayout(self.layoutPrefix, 0, 2, 1, 1)
        self.listWorkspaces = QtGui.QListWidget(SaveDialog)
        self.listWorkspaces.setObjectName(_fromUtf8("listWorkspaces"))
        self.layoutMain.addWidget(self.listWorkspaces, 2, 0, 1, 1)
        self.labelWorkspaces = QtGui.QLabel(SaveDialog)
        self.labelWorkspaces.setObjectName(_fromUtf8("labelWorkspaces"))
        self.layoutMain.addWidget(self.labelWorkspaces, 1, 0, 1, 1)
        self.buttonsMain = QtGui.QDialogButtonBox(SaveDialog)
        self.buttonsMain.setOrientation(QtCore.Qt.Horizontal)
        self.buttonsMain.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Save)
        self.buttonsMain.setCenterButtons(True)
        self.buttonsMain.setObjectName(_fromUtf8("buttonsMain"))
        self.layoutMain.addWidget(self.buttonsMain, 4, 0, 1, 3)
        self.labelParameters = QtGui.QLabel(SaveDialog)
        self.labelParameters.setObjectName(_fromUtf8("labelParameters"))
        self.layoutMain.addWidget(self.labelParameters, 1, 2, 1, 1)
        self.layoutPath = QtGui.QHBoxLayout()
        self.layoutPath.setObjectName(_fromUtf8("layoutPath"))
        self.labelPath = QtGui.QLabel(SaveDialog)
        self.labelPath.setObjectName(_fromUtf8("labelPath"))
        self.layoutPath.addWidget(self.labelPath)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.layoutPath.addItem(spacerItem2)
        self.textPath = QtGui.QLineEdit(SaveDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textPath.sizePolicy().hasHeightForWidth())
        self.textPath.setSizePolicy(sizePolicy)
        self.textPath.setObjectName(_fromUtf8("textPath"))
        self.layoutPath.addWidget(self.textPath)
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.layoutPath.addItem(spacerItem3)
        self.buttonBrowse = QtGui.QPushButton(SaveDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBrowse.sizePolicy().hasHeightForWidth())
        self.buttonBrowse.setSizePolicy(sizePolicy)
        self.buttonBrowse.setMinimumSize(QtCore.QSize(0, 0))
        self.buttonBrowse.setMaximumSize(QtCore.QSize(25, 16777215))
        self.buttonBrowse.setObjectName(_fromUtf8("buttonBrowse"))
        self.layoutPath.addWidget(self.buttonBrowse)
        self.layoutMain.addLayout(self.layoutPath, 0, 0, 1, 1)
        self.layoutBottomLeft = QtGui.QVBoxLayout()
        self.layoutBottomLeft.setObjectName(_fromUtf8("layoutBottomLeft"))
        self.layoutSpectra = QtGui.QHBoxLayout()
        self.layoutSpectra.setObjectName(_fromUtf8("layoutSpectra"))
        self.labelSpectra = QtGui.QLabel(SaveDialog)
        self.labelSpectra.setObjectName(_fromUtf8("labelSpectra"))
        self.layoutSpectra.addWidget(self.labelSpectra)
        self.textSpectra = QtGui.QLineEdit(SaveDialog)
        self.textSpectra.setObjectName(_fromUtf8("textSpectra"))
        self.layoutSpectra.addWidget(self.textSpectra)
        self.layoutBottomLeft.addLayout(self.layoutSpectra)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.layoutBottomLeft.addItem(spacerItem4)
        self.layoutFormat = QtGui.QHBoxLayout()
        self.layoutFormat.setObjectName(_fromUtf8("layoutFormat"))
        self.labelFormat = QtGui.QLabel(SaveDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFormat.sizePolicy().hasHeightForWidth())
        self.labelFormat.setSizePolicy(sizePolicy)
        self.labelFormat.setMaximumSize(QtCore.QSize(60, 16777215))
        self.labelFormat.setObjectName(_fromUtf8("labelFormat"))
        self.layoutFormat.addWidget(self.labelFormat)
        spacerItem5 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.layoutFormat.addItem(spacerItem5)
        self.comboFormat = QtGui.QComboBox(SaveDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboFormat.sizePolicy().hasHeightForWidth())
        self.comboFormat.setSizePolicy(sizePolicy)
        self.comboFormat.setMinimumSize(QtCore.QSize(150, 0))
        self.comboFormat.setObjectName(_fromUtf8("comboFormat"))
        self.layoutFormat.addWidget(self.comboFormat)
        self.layoutBottomLeft.addLayout(self.layoutFormat)
        self.layoutMain.addLayout(self.layoutBottomLeft, 3, 0, 1, 1)
        self.groupFormatOps = QtGui.QGroupBox(SaveDialog)
        self.groupFormatOps.setObjectName(_fromUtf8("groupFormatOps"))
        self.layoutFormatOps = QtGui.QVBoxLayout(self.groupFormatOps)
        self.layoutFormatOps.setObjectName(_fromUtf8("layoutFormatOps"))
        self.checkTitle = QtGui.QCheckBox(self.groupFormatOps)
        self.checkTitle.setObjectName(_fromUtf8("checkTitle"))
        self.layoutFormatOps.addWidget(self.checkTitle)
        self.checkQres = QtGui.QCheckBox(self.groupFormatOps)
        self.checkQres.setObjectName(_fromUtf8("checkQres"))
        self.layoutFormatOps.addWidget(self.checkQres)
        self.groupSeparator = QtGui.QGroupBox(self.groupFormatOps)
        self.groupSeparator.setObjectName(_fromUtf8("groupSeparator"))
        self.layoutSeparator = QtGui.QHBoxLayout(self.groupSeparator)
        self.layoutSeparator.setObjectName(_fromUtf8("layoutSeparator"))
        self.radioComma = QtGui.QRadioButton(self.groupSeparator)
        self.radioComma.setObjectName(_fromUtf8("radioComma"))
        self.layoutSeparator.addWidget(self.radioComma)
        self.radioSpace = QtGui.QRadioButton(self.groupSeparator)
        self.radioSpace.setObjectName(_fromUtf8("radioSpace"))
        self.layoutSeparator.addWidget(self.radioSpace)
        self.radioTab = QtGui.QRadioButton(self.groupSeparator)
        self.radioTab.setObjectName(_fromUtf8("radioTab"))
        self.layoutSeparator.addWidget(self.radioTab)
        self.layoutFormatOps.addWidget(self.groupSeparator)
        self.layoutMain.addWidget(self.groupFormatOps, 3, 2, 1, 1)
        self.listParameters = QtGui.QListWidget(SaveDialog)
        self.listParameters.setObjectName(_fromUtf8("listParameters"))
        self.layoutMain.addWidget(self.listParameters, 2, 2, 1, 1)
        self.labelPrefix.setBuddy(self.textPrefix)
        self.labelWorkspaces.setBuddy(self.listWorkspaces)
        self.labelParameters.setBuddy(self.listParameters)
        self.labelPath.setBuddy(self.textPath)
        self.labelSpectra.setBuddy(self.textSpectra)
        self.labelFormat.setBuddy(self.comboFormat)

        self.retranslateUi(SaveDialog)
        QtCore.QObject.connect(self.buttonsMain, QtCore.SIGNAL(_fromUtf8("rejected()")), SaveDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SaveDialog)
        SaveDialog.setTabOrder(self.textPath, self.buttonBrowse)
        SaveDialog.setTabOrder(self.buttonBrowse, self.textPrefix)
        SaveDialog.setTabOrder(self.textPrefix, self.listWorkspaces)
        SaveDialog.setTabOrder(self.listWorkspaces, self.listParameters)
        SaveDialog.setTabOrder(self.listParameters, self.textSpectra)
        SaveDialog.setTabOrder(self.textSpectra, self.comboFormat)
        SaveDialog.setTabOrder(self.comboFormat, self.checkTitle)
        SaveDialog.setTabOrder(self.checkTitle, self.checkQres)
        SaveDialog.setTabOrder(self.checkQres, self.radioComma)
        SaveDialog.setTabOrder(self.radioComma, self.radioSpace)
        SaveDialog.setTabOrder(self.radioSpace, self.radioTab)
        SaveDialog.setTabOrder(self.radioTab, self.buttonsMain)

    def retranslateUi(self, SaveDialog):
        SaveDialog.setWindowTitle(QtGui.QApplication.translate("SaveDialog", "Export Workspaces", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonTransfer.setText(QtGui.QApplication.translate("SaveDialog", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPrefix.setText(QtGui.QApplication.translate("SaveDialog", "Prefix:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelWorkspaces.setText(QtGui.QApplication.translate("SaveDialog", "List of workspaces:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelParameters.setText(QtGui.QApplication.translate("SaveDialog", "List of logged parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPath.setText(QtGui.QApplication.translate("SaveDialog", "Save Path", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonBrowse.setText(QtGui.QApplication.translate("SaveDialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSpectra.setText(QtGui.QApplication.translate("SaveDialog", "Spectra List:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFormat.setText(QtGui.QApplication.translate("SaveDialog", "File Format:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupFormatOps.setTitle(QtGui.QApplication.translate("SaveDialog", "Custom format options", None, QtGui.QApplication.UnicodeUTF8))
        self.checkTitle.setText(QtGui.QApplication.translate("SaveDialog", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.checkQres.setText(QtGui.QApplication.translate("SaveDialog", "Q resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.groupSeparator.setTitle(QtGui.QApplication.translate("SaveDialog", "Separator", None, QtGui.QApplication.UnicodeUTF8))
        self.radioComma.setText(QtGui.QApplication.translate("SaveDialog", "Comma", None, QtGui.QApplication.UnicodeUTF8))
        self.radioSpace.setText(QtGui.QApplication.translate("SaveDialog", "Space", None, QtGui.QApplication.UnicodeUTF8))
        self.radioTab.setText(QtGui.QApplication.translate("SaveDialog", "Tab", None, QtGui.QApplication.UnicodeUTF8))

